apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-risk-assessment-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.global.cronTab }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

  jobTemplate:
    metadata:
      labels:
        app: k8s-risk-assessment-job
    spec:
      template:
        metadata:
          labels:
            app: scanner
        spec:
        {{- if .Values.global.registry.secretName }}
          imagePullSecrets:
          - name: {{ .Values.global.registry.secretName }}-k8s
        {{- end }}
          {{- if .Values.global.nodeSelector }}
          nodeSelector:
            {{- toYaml .Values.global.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.global.tolerations }}
          tolerations:
            {{- toYaml .Values.global.tolerations | nindent 12 }}
          {{- end }}
          securityContext:
            fsGroup: 1000
          initContainers:
            {{- include "risk-assessment.container" . | nindent 12 }}
          containers:
            {{- include "risk-assessment.uploader" . | nindent 12 }}
          volumes:
            {{- include "risk-assessment.volumes" . | nindent 12 }}
          restartPolicy: Never
          serviceAccount: k8s-risk-assessment-job-service-account
