apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-risk-assessment-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.global.cronTab }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

  jobTemplate:
    metadata:
      labels:
        app: k8s-risk-assessment-job
    spec:
      template:
        spec:
        {{- if .Values.registry.secretName }}
          imagePullSecrets:
          - name: {{ .Values.registry.secretName }}
        {{- end }}        
          initContainers:
            - name: job-init-container
              image: "{{ include "kubescape.image" . }}"
              args:
                - scan
                - framework
                - allcontrols,clusterscan,mitre,nsa
                - --format
                - json
                - --cache-dir
                - /data/kubescape-cache
                - --output
                - /data/report.json
                - --cluster-name=$(CLUSTER_NAME)
                {{- if .Values.airgapped }}
                - --use-artifacts-from
                - /opt/kubescape/artifacts
                {{- end }}
              env:
                - name: CLUSTER_NAME
                  value: {{ .Values.global.clusterName }}
              volumeMounts:
                - name: datapath
                  mountPath: /data
          containers:
            - image: "{{ include "cluster_job.image" . }}"
              name: artifact-api-container
              command:
                - '/bin/sh'
                - '/script/augment-and-push-results.sh'
              env:
                - name: AUTH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: AUTH_TOKEN
                      {{- if (.Values.global.secretName | empty) }}
                      name: k8s-risk-assessment-job-auth-token
                      {{- else }}
                      name: {{ .Values.global.secretName }}
                      {{- end }}
                - name: URL
                  value: {{ include "global.jobURL" . }}
                - name: TENANT_ID
                  value: {{ .Values.global.tenantId | quote }}
                - name: CLUSTER_NAME
                  value: {{ .Values.global.clusterName }}
                - name: CLUSTER_ID
                  value: {{ .Values.global.clusterID | quote }}
                - name: LABEL_NAME
                  value: {{ .Values.global.label }}
              volumeMounts:
                - mountPath: /data
                  name: datapath
                - mountPath: /script
                  name: scriptpath
          volumes:
            - name: datapath
              emptyDir: {}
            - name: scriptpath
              configMap:
                name: k8s-risk-assessment-job-script-configmap
          restartPolicy: OnFailure
          serviceAccount: k8s-risk-assessment-job-service-account
