apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-risk-assessment-job-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      labels:
        app: k8s-risk-assessment-job-{{ now | unixEpoch }}
    spec:
    {{- if .Values.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.registry.secretName }}
    {{- end }}     
      initContainers:
        - name: job-init-container
          image: "{{ include "kubescape.image" . }}"
          args:
            - scan
            - framework
            - allcontrols,clusterscan,mitre,nsa
            - --format
            - json
            - --cache-dir
            - /data/kubescape-cache
            - --output
            - /data/report.json
            - --cluster-name=$(CLUSTER_NAME)
            {{- if .Values.global.airgapped }}
            - --use-artifacts-from
            - /opt/kubescape/artifacts
            {{- end }}
          env:
            - name: CLUSTER_NAME
              value: "{{ .Values.global.clusterName }}"
          volumeMounts:
            - name: datapath
              mountPath: /data
      containers:
        - image: "{{ include "cluster_job.image" . }}"
          name: artifact-api-container
          args: 
          - -config 
          - /jobs/conf/app.yaml
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data
              name: datapath
            - mountPath: /script
              name: scriptpath
            - name: secret-volume
              mountPath: /secrets/tokens
              readOnly: true
            - name: config
              mountPath: /jobs/conf/app.yaml
              subPath: app.yaml
            {{- if eq (include "spire.enabled" . ) "true" }}   
            - name: config
              mountPath: /jobs/spire/agent.conf
              subPath: agent.conf 
            - name: spirepath
              mountPath: /run/spire/agent
            {{- end }}
      volumes:
        - name: datapath
          emptyDir: {}
        - name: scriptpath
          configMap:
            name: k8s-risk-assessment-job-script-configmap
        - name: secret-volume
          secret:
            secretName: {{ .Values.global.secretName | default "jobs-token" }}
        - name: config
          configMap:
            name: risk-assessment-config-{{ .Release.Name }}
        {{- if eq (include "spire.enabled" . ) "true" }}
        - name: spirepath
          emptyDir: {}
        {{- end }}
      restartPolicy: OnFailure
      serviceAccount: k8s-risk-assessment-job-service-account