apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-risk-assessment-job-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      labels:
        job-name: k8s-risk-assessment-job-{{ now | unixEpoch }}
        app: scanner
    spec:
    {{- if .Values.global.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.global.registry.secretName }}-k8s
    {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      containers:
        {{- include "risk-assessment.container" . | nindent 8 }}
      volumes:
        {{- include "risk-assessment.volumes" . | nindent 8 }}
      restartPolicy: OnFailure
      serviceAccount: k8s-risk-assessment-job-service-account
