{{- if (.Values.global.secretName | empty) }}
# if user didn't specify a secretName, use the default
apiVersion: v1
kind: Secret
metadata:
  name: k8s-risk-assessment-job-token
  namespace: {{ .Release.Namespace }}
data:
  AUTH_TOKEN: {{ .Values.global.authToken | b64enc }}
  JOIN_TOKEN: {{ .Values.global.agents.joinToken | b64enc }}
{{- end }}