{{- if .Values.feederService.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "feederService.name" . }}
  labels:
    app: {{ include "feederService.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "feederService.name" . }}
{{- end }}
