{
 "title": "Events",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(feeder_events_received,namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(feeder_events_received{namespace=\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate of Events Received by Entity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (entity_type) (rate(feeder_events_received{namespace=\"$namespace\",service=\"$instance\"}[$__range]))",
     "legendFormat": "{{entity_type}}"
    }
   ]
  },
  {
   "title": "Total Rate of Events Received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(feeder_events_received{namespace=\"$namespace\", service=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Rate of Events Pushed by Entity and Integration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (entity_type, integration) (rate(feeder_events_pushed{namespace=\"$namespace\", service=\"$instance\"}[$__range]))",
     "legendFormat": "{{entity_type}} ({{integration}})"
    }
   ]
  },
  {
   "title": "Total Rate of Events Pushed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(feeder_events_pushed{namespace=\"$namespace\", service=\"$instance\"}[$__range]))"
    }
   ]
  }
 ]
}