{{- if (eq (include "condition-feeder" .) "false") }}
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: {{ include "sharedInformerAgent.name" . }}
  namespace: {{ .Release.Namespace }}
data: 
  app.yaml: |-
    spire:
      enable: {{ .Values.agentsOperator.spireVars.SPIRE_ENABLED }}

      agent: "agents-operator.{{ .Release.Namespace }}.svc.cluster.local:9091"
    kmux-topic: cluster-entity/shared-event    
    kmux-topic-prefix: 

    heartbeat:
      interval: 5m
    
    resource-refresh:
      interval: 30m
      resync: 30m

    psa:
      violation-topic: admissionevents
      audit-webhook-port: {{ .Values.sharedInformerAgent.auditWebhook.port | default 8080 }}
    knoxguard:
      topic: knoxguardevents
    deployMode: "k8s"

    k8s:
      enable: true

    informers:
      service: false
      statefulset: true
      deployment: true
      daemonset: true
      replicaset: true
      job: true
      cronjob: true
      pod: true
      namespace: true
      node: true

    log:
      level: info

    metrics:
      enable: false
      port: 2122

{{- end }}   
