{{- if (eq (include "condition-feeder" .) "false") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sharedInformerAgent.name" . }}
  namespace: {{ .Release.Namespace }}

---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sharedInformerAgent.name" . }}
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"] 
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"] 
- apiGroups: ["batch"]
  resources: ["cronjobs","jobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sharedInformerAgent.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sharedInformerAgent.name" . }} 
subjects:
- kind: ServiceAccount
  name: {{ include "sharedInformerAgent.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}  
