apiVersion: batch/v1
kind: CronJob
metadata:
  name: cis-k8s-cronjob
  namespace: {{ .Release.Namespace }}
spec:
  jobTemplate:
    metadata:
      name: cis-k8s-cronjob
    spec:
      template:
        spec:
        {{- if or (or (contains "master" .Values.toolConfig.nodeType) (contains "controlplane" .Values.toolConfig.nodeType)) (or (contains "master" .Values.toolConfig.targets) (contains "controlplane" .Values.toolConfig.targets)) }}
          {{- include "masterConfig" .Values.toolConfig | trim | nindent 10 }}
        {{- end }}
          {{- if .Values.registry.secretName }}
          imagePullSecrets:
          - name: {{ .Values.registry.secretName | quote }}
          {{- end }}
          {{- if .Values.joinToken }}
          serviceAccount: cis-service-account
          {{- end }}
          containers:
          - image: "{{ include "cluster_job.image" . }}"
            args: 
            - -config 
            - /jobs/conf/app.yaml
            name: cis-k8s-cronjob
            volumeMounts:
            - mountPath: /data
              name: datapath
            - name: secret-volume
              mountPath: /secrets/tokens
              readOnly: true
            - name: config
              mountPath: /jobs/conf/app.yaml
              subPath: app.yaml
            {{- if .Values.joinToken }}    
            - name: config
              mountPath: /jobs/spire/agent.conf
              subPath: agent.conf 
            - name: spirepath
              mountPath: /run/spire/agent
            {{- end }}
          initContainers:
          - image: "{{ include "kubeBench.image" . }}"
            command:
            {{- include "cmd" .Values.toolConfig | trim | nindent 13 }}
            name: kube-bench
            volumeMounts:
            {{- include "volumeMounts" .Values.toolConfig | trim | nindent 13 }}
          hostPID: true
          restartPolicy: Never
          volumes:
           - name: secret-volume
             secret:
               secretName: {{ .Values.secretName | default "cis-k8s-job-token" }}
           - name: config
             configMap:
               name: cis-config-{{ .Release.Name }}
           {{- if .Values.joinToken }} 
           - name: spirepath
             emptyDir: {}
           {{- end }}
          {{- include "volumes" .Values.toolConfig | trim | nindent 11 }}

  schedule: "{{ .Values.cronTab }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

status: {}
