apiVersion: batch/v1
kind: Job
metadata:
  name: cis-k8s-job
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: cis-k8s-job
      labels:
        app: cis-k8s-job   
    spec:
    {{- if .Values.imagePullSecrets.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
    {{- end }}    
      containers:
      - image: "{{ .Values.accuknoxJob.image.repository }}:{{ .Values.accuknoxJob.image.tag }}" 
        command: ["/bin/sh", "-c"]
        args: ['/bin/sh entrypoint.sh && curl --location --request POST "https://${URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=KB&label_id=${LABEL_NAME}&save_to_s3=true" --header "Tenant-Id: ${TENANT_ID}" --header "Authorization: Bearer ${AUTH_TOKEN}" --form "file=@\"./data/report.json\"" && cat /data/report.json']
        name: cis-k8s-cronjob
        resources: {}
        env:
          - name: AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                key: AUTH_TOKEN
                {{- if (.Values.accuknox.secretName | empty) }}
                name: cis-k8s-job-auth-token
                {{- else }}
                name: {{ .Values.accuknox.secretName }}
                {{- end }}
          - name: CLUSTER_NAME
            value: {{ .Values.accuknox.clusterName }}
          - name: LABEL_NAME
            value: {{ .Values.accuknox.label }}
          - name: CLUSTER_ID
            value: {{ .Values.accuknox.clusterId }}
          - name: TENANT_ID
            value: {{ .Values.accuknox.tenantId | quote}}
          - name: URL
            value: {{ .Values.accuknox.url }}
        volumeMounts:
        - mountPath: /data
          name: datapath
      initContainers:
      - image: "{{ .Values.kubeBench.image.repository }}:{{ .Values.kubeBench.image.tag }}" 
        command: ["/bin/sh", "-c"]
        args: ["kube-bench run --json > /data/report.json"]
        name: kube-bench
        volumeMounts:
        - mountPath: /data
          name: datapath
        - mountPath: /var/lib/etcd
          name: var-lib-etcd
          readOnly: true
        - mountPath: /var/lib/kubelet
          name: var-lib-kubelet
          readOnly: true
        - mountPath: /var/lib/kube-scheduler
          name: var-lib-kube-scheduler
          readOnly: true
        - mountPath: /var/lib/kube-controller-manager
          name: var-lib-kube-controller-manager
          readOnly: true
        - mountPath: /etc/systemd
          name: etc-systemd
          readOnly: true
        - mountPath: /lib/systemd/
          name: lib-systemd
          readOnly: true
        - mountPath: /srv/kubernetes/
          name: srv-kubernetes
          readOnly: true
        - mountPath: /etc/kubernetes
          name: etc-kubernetes
          readOnly: true
        - mountPath: /usr/local/mount-from-host/bin
          name: usr-bin
          readOnly: true
        - mountPath: /etc/cni/net.d/
          name: etc-cni-netd
          readOnly: true
        - mountPath: /opt/cni/bin/
          name: opt-cni-bin
          readOnly: true
      hostPID: true
      restartPolicy: Never
      volumes:
        - name: datapath
          emptyDir: {}
        - hostPath:
            path: /var/lib/etcd
          name: var-lib-etcd
        - hostPath:
            path: /var/lib/kubelet
          name: var-lib-kubelet
        - hostPath:
            path: /var/lib/kube-scheduler
          name: var-lib-kube-scheduler
        - hostPath:
            path: /var/lib/kube-controller-manager
          name: var-lib-kube-controller-manager
        - hostPath:
            path: /etc/systemd
          name: etc-systemd
        - hostPath:
            path: /lib/systemd
          name: lib-systemd
        - hostPath:
            path: /srv/kubernetes
          name: srv-kubernetes
        - hostPath:
            path: /etc/kubernetes
          name: etc-kubernetes
        - hostPath:
            path: /usr/bin
          name: usr-bin
        - hostPath:
            path: /etc/cni/net.d/
          name: etc-cni-netd
        - hostPath:
            path: /opt/cni/bin/
          name: opt-cni-bin
