apiVersion: batch/v1
kind: Job
metadata:
  name: cis-k8s-job-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      name: cis-k8s-job-{{ now | unixEpoch }}
      labels:
        app: cis-k8s-job-{{ now | unixEpoch }}
    spec:
    {{- if or (or (contains "master" .Values.toolConfig.nodeType) (contains "controlplane" .Values.toolConfig.nodeType)) (or (contains "master" .Values.toolConfig.targets) (contains "controlplane" .Values.toolConfig.targets)) }}
      {{- include "masterConfig" .Values.toolConfig | trim | nindent 6 }}
    {{- end }}
      {{- if .Values.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.registry.secretName | quote }}
      {{- end }}
      containers:
      - serviceAccount: cis-service-account
        image: "{{ include "cluster_job.image" . }}"
        args: 
        - -config 
        - /jobs/conf/app.yaml
        name: cis-k8s-cronjob
        volumeMounts:
        - mountPath: /data
          name: datapath
        - name: secret-volume
          mountPath: /secrets/tokens
          readOnly: true
        {{- if .Values.joinToken }}    
        - name: config
          mountPath: /jobs/spire/
          subPath: agent.conf 
        - name: spirepath
          mountPath: /run/spire/agent
        - name: config
          mountPath: /jobs/conf/
          subPath: app.yaml
        {{- end }}
      initContainers:
      - image: "{{ include "kubeBench.image" . }}"
        command:
        {{- include "cmd" .Values.toolConfig | trim | nindent 9 }}
        name: kube-bench
        volumeMounts:
        {{- include "volumeMounts" .Values.toolConfig | trim | nindent 9 }}
      hostPID: true
      restartPolicy: Never
      volumes:
       - name: secret-volume
         secret:
           secretName: {{ .Values.secretName | default "cis-k8s-job-token" }}
       {{- if .Values.joinToken }} 
       - name: spirepath
         emptyDir: {}
       - name: config
         configMap:
           name: cis-config-{{ .Release.Name }}
       {{- end }}
      {{- include "volumes" .Values.toolConfig | trim | nindent 7 }}
