apiVersion: batch/v1
kind: CronJob
metadata:
  name: cis-k8s-cronjob
  namespace: {{ .Release.Namespace }}
spec:
  jobTemplate:
    metadata:
      name: cis-k8s-cronjob
    spec:
      template:
        metadata:
          labels:
            app: scanner
        spec:
        {{- if or (or (contains "master" .Values.global.cis.toolConfig.nodeType) (contains "controlplane" .Values.global.cis.toolConfig.nodeType)) (or (contains "master" .Values.global.cis.toolConfig.targets) (contains "controlplane" .Values.global.cis.toolConfig.targets)) }}
          {{- include "masterConfig" .Values.global.cis.toolConfig | trim | nindent 10 }}
        {{- end }}
          {{- if .Values.global.registry.secretName }}
          imagePullSecrets:
          - name: {{ .Values.global.registry.secretName }}-cis
          {{- end }}
          {{- if .Values.global.nodeSelector }}
          nodeSelector:
            {{- toYaml .Values.global.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.global.tolerations }}
          tolerations:
            {{- toYaml .Values.global.tolerations | nindent 12 }}
          {{- end }}
          serviceAccount: cis-service-account
          containers:
          - image: "{{ include "cluster_job.image" . }}"
            args: 
            - -config 
            - /jobs/conf/app.yaml
            name: cis-k8s-cronjob
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - mountPath: /data
              name: datapath
            - name: secret-volume
              mountPath: /secrets/tokens
              readOnly: true
            - name: config
              mountPath: /jobs/conf/app.yaml
              subPath: app.yaml
            {{- if .Values.global.certEnabled }}
            - name: certs
              mountPath: /certs
              readOnly: true
            {{- end }}           
            {{- if eq (include "spire.enabled" . ) "true" }}    
            - name: config
              mountPath: /jobs/spire/agent.conf
              subPath: agent.conf 
            - name: spirepath
              mountPath: /run/spire/agent
            {{- end }}
          initContainers:
          - image: "{{ include "kubeBench.image" . }}"
            command:
            {{- include "cmd" .Values.global.cis.toolConfig | trim | nindent 13 }}
            name: kube-bench
            imagePullPolicy: IfNotPresent
            volumeMounts:
            {{- include "volumeMounts" (dict "platform" .Values.global.cis.toolConfig.platform "targets" .Values.global.cis.toolConfig.targets "benchmark" .Values.global.cis.toolConfig.benchmark "check" .Values.global.cis.toolConfig.check "skip" .Values.global.cis.toolConfig.skip "talosEnv" .Values.global.talosEnv) | trim | nindent 13 }}         
          hostPID: true
          restartPolicy: Never
          volumes:
           - name: secret-volume
             secret:
               secretName: {{ .Values.global.secretName | default "jobs-token" }}
           - name: config
             configMap:
               name: cis-config-{{ .Release.Name }}
          {{- if .Values.global.certEnabled }}
           - name: certs
             secret:
               secretName: {{ .Values.global.certSecretName | default "jobs-cert" }}
          {{- end }}     
           {{- if eq (include "spire.enabled" . ) "true" }} 
           - name: spirepath
             emptyDir: {}
           {{- end }}
          {{- include "volumes" (dict "platform" .Values.global.cis.toolConfig.platform "targets" .Values.global.cis.toolConfig.targets "benchmark" .Values.global.cis.toolConfig.benchmark "check" .Values.global.cis.toolConfig.check "skip" .Values.global.cis.toolConfig.skip "talosEnv" .Values.global.talosEnv) | trim | nindent 11 }}

  schedule: "{{ .Values.global.cronTab }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

status: {}