{{- if .Values.global.certEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.certSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ .Values.global.certPath | b64enc }}
{{- end }}