apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cis-cluster-role-readonly
rules:
- apiGroups: [""]
  resources:
    - secrets
    - serviceaccounts
    - configmaps
    - services
    - pods
    - endpoints
    - replicationcontrollers
  verbs: ["get", "list"]

- apiGroups: ["admissionregistration.k8s.io"]
  resources:
    - validatingwebhookconfigurations
    - mutatingwebhookconfigurations
  verbs: ["get", "list"]

- apiGroups: ["policy"]
  resources:
    - podsecuritypolicies
  verbs: ["get", "list"]

- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - "roles"
    - "rolebindings"
    - "clusterroles"
    - "clusterrolebindings"
  verbs: ["get", "list"]

- apiGroups: ["apps"]
  resources:
    - deployments
    - daemonsets
    - statefulsets
    - replicasets
  verbs: ["get", "list"]

- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["get", "list"]

- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
  verbs: ["get", "list"]