apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cis-cluster-role-readonly
rules:
- apiGroups: [""]
  resources:
    - secrets
    - serviceaccounts
    - configmaps
    - services
  verbs: ["get", "list"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources:
    - validatingwebhookconfigurations
    - mutatingwebhookconfigurations
  verbs: ["get", "list"]
- apiGroups: ["policy"]
  resources:
    - podsecuritypolicies
  verbs: ["get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - "roles"
    - "rolebindings"
    - "clusterroles"
    - "clusterrolebindings"
  verbs: ["get", "list"]
