apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-risk-assessment-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.cronTab }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

  jobTemplate:
    metadata:
      labels:
        app: k8s-risk-assessment-job
    spec:
      template:
        spec:
        {{- if .Values.registry.secretName }}
          imagePullSecrets:
          - name: {{ .Values.registry.secretName }}
        {{- end }}        
          initContainers:
            - name: job-init-container
              image: "{{ include "kubescape.image" . }}"
              args: ["scan", "framework", "allcontrols,clusterscan,mitre,nsa", "--format", "json", "--cache-dir", "/data/kubescape-cache", "--output", "/data/report.json", "--cluster-name=$(CLUSTER_NAME)"]
              env:
                - name: CLUSTER_NAME
                  value: {{ .Values.clusterName }}
              volumeMounts:
                - name: datapath
                  mountPath: /data
          containers:
            - image: "{{ include "cluster_job.image" . }}"
              name: artifact-api-container
              command:
                - '/bin/sh'
                - '/script/augment-and-push-results.sh'
              env:
                - name: AUTH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: AUTH_TOKEN
                      {{- if (.Values.secretName | empty) }}
                      name: k8s-risk-assessment-job-auth-token
                      {{- else }}
                      name: {{ .Values.secretName }}
                      {{- end }}
                - name: URL
                  value: {{ .Values.URL }}
                - name: TENANT_ID
                  value: {{ .Values.tenantID | quote }}
                - name: CLUSTER_NAME
                  value: {{ .Values.clusterName }}
                - name: CLUSTER_ID
                  value: {{ .Values.clusterID | quote }}
                - name: LABEL_NAME
                  value: {{ .Values.label }}
              volumeMounts:
                - mountPath: /data
                  name: datapath
                - mountPath: /script
                  name: scriptpath
          volumes:
            - name: datapath
              emptyDir: {}
            - name: scriptpath
              configMap:
                name: k8s-risk-assessment-job-script-configmap
          restartPolicy: OnFailure
          serviceAccount: k8s-risk-assessment-job-service-account
