apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-risk-assessment-job
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: k8s-risk-assessment-job
    spec:
    {{- if .Values.imagePullSecrets.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
    {{- end }}    
      initContainers:
        - name: job-init-container
          image: "{{ .Values.kubescape.image.repository }}:{{ .Values.kubescape.image.tag }}"
          args: ["scan", "framework", "allcontrols,clusterscan,mitre,nsa", "--format", "json", "--cache-dir", "/data/kubescape-cache", "--output", "/data/report.json", "--cluster-name=$(CLUSTER_NAME)"]
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.accuknox.clusterName }}
          volumeMounts:
            - name: datapath
              mountPath: /data
      containers:
        - image: "{{ .Values.accuknoxJob.image.repository }}:{{ .Values.accuknoxJob.image.tag }}"
          name: artifact-api-container
          command:
            - '/bin/sh'
            - '/script/augment-and-push-results.sh'
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: AUTH_TOKEN
                  {{- if (.Values.accuknox.secretName | empty) }}
                  name: k8s-risk-assessment-job-auth-token
                  {{- else }}
                  name: {{ .Values.accuknox.secretName }}
                  {{- end }}
            - name: URL
              value: {{ .Values.accuknox.URL }}
            - name: TENANT_ID
              value: {{ .Values.accuknox.tenantID | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.accuknox.clusterName }}
            - name: CLUSTER_ID
              value: {{ .Values.accuknox.clusterID | quote }}
            - name: LABEL_NAME
              value: {{ .Values.accuknox.label }}
          volumeMounts:
            - mountPath: /data
              name: datapath
            - mountPath: /script
              name: scriptpath
      volumes:
        - name: datapath
          emptyDir: {}
        - name: scriptpath
          configMap:
            name: k8s-risk-assessment-job-script-configmap
      restartPolicy: OnFailure
      serviceAccount: k8s-risk-assessment-job-service-account
