apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-risk-assessment-job-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      labels:
        app: k8s-risk-assessment-job-{{ now | unixEpoch }}
    spec:
    {{- if .Values.imagePullSecrets.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
    {{- end }}    
      initContainers:
        - name: job-init-container
          image: "{{ .Values.kubescape.image.repository }}:{{ .Values.kubescape.image.tag }}"
          args: ["scan", "framework", "allcontrols,clusterscan,mitre,nsa", "--format", "json", "--cache-dir", "/data/kubescape-cache", "--output", "/data/report.json", "--cluster-name=$(CLUSTER_NAME)"]
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.accuknox.clusterName }}
          volumeMounts:
            - name: datapath
              mountPath: /data
      containers:
        - image: "{{ .Values.accuknoxJob.image.repository }}:{{ .Values.accuknoxJob.image.tag }}"
          name: artifact-api-container
          command: ["/bin/sh", "-c"]
          args: 
          - '/home/jobs/job -url  "https://${URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=KS&save_to_s3=true&label_id=${LABEL_NAME}"'
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: AUTH_TOKEN
                  {{- if (.Values.accuknox.secretName | empty) }}
                  name: k8s-risk-assessment-job-auth-token
                  {{- else }}
                  name: {{ .Values.accuknox.secretName }}
                  {{- end }}
            - name: URL
              value: {{ .Values.accuknox.URL }}
            - name: TENANT_ID
              value: {{ .Values.accuknox.tenantID | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.accuknox.clusterName }}
            - name: CLUSTER_ID
              value: {{ .Values.accuknox.clusterID | quote }}
            - name: LABEL_NAME
              value: {{ .Values.accuknox.label }}
            - name: DATA_TYPE
              value: {{ .Values.accuknox.dataType | default "KS" }}
            - name:  "SAVE_TO_S3"
              value: {{ .Values.accuknox.saveToS3 | default "false" }}
            - name:  "REPORT_FILE"
              value: {{ .Values.accuknox.reportFile | default "/data/report.json" }}
            - name:  "SPIRE_SERVER"
              value: {{ .Values.spire.server }}
            - name:  "SPIRE_PORT"
              value: {{ .Values.spire.port | default "8081" | quote }}
            - name:  "SPIRE_SECRET_NAME"
              value: {{ .Values.spire.secretName | default (printf "spire-agent-secret-%s" .Release.Name) }}
            - name:  "SPIRE_JOIN_TOKEN"
              value: {{ .Values.spire.joinToken }}
            - name:  "SPIRE_NAMESPACE"
              value: {{ .Release.Namespace }}
            - name:  "SPIRE_CONFIG_PATH"
              value: {{ .Values.spire.configPath | default "/spire/agent.conf" | quote }}
            - name:  "KNOX_GATEWAY"
              value: {{ .Values.accuknox.gateway }}
            - name: "PRINT_DATA"
              value: "true"
          volumeMounts:
            - mountPath: /data
              name: datapath
            - mountPath: /script
              name: scriptpath
            {{- if .Values.spire.joinToken }}    
            - name: spire-agent
              mountPath: /spire/ 
            - name: spirepath
              mountPath: /run/spire/agent
            {{- end }}
      volumes:
        - name: datapath
          emptyDir: {}
        - name: scriptpath
          configMap:
            name: k8s-risk-assessment-job-script-configmap
        {{- if .Values.spire.joinToken }} 
        - name: spirepath
          emptyDir: {}
        - name: spire-agent
          configMap:
            name: {{ printf "spire-agent-config-%s" .Release.Name }} 
        {{- end }}
      restartPolicy: OnFailure
      serviceAccount: k8s-risk-assessment-job-service-account
