{{- if (.Values.accuknox.secretName | empty) }}
# if user didn't specify a secretName, use the default
apiVersion: v1
kind: Secret
metadata:
  name: k8s-risk-assessment-job-auth-token
  namespace: {{ .Release.Namespace }}
data:
  AUTH_TOKEN: {{ .Values.accuknox.authToken | b64enc }}
{{- end }}
