{{- if and (.Values.rabbitmq.enabled) (.Values.install.localRegistryAgent)}}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.username | b64enc | quote }}
  password: {{ .Values.rabbitmq.password | b64enc | quote }}
{{- end }}
