apiVersion: batch/v1
kind: CronJob
metadata:
  name: kiem-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.cronTab }}"  
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: kiem-job
    spec:
      template:
        spec:
        {{- if .Values.registry.secretName }}
          imagePullSecrets:
          - name: {{ .Values.registry.secretName }}
        {{- end }}         
          initContainers:
            - name: kiem-init
              image: "{{ include "kiem.image" . }}"
              args: ["./kiem", "run", "--mode", "k8s", "--output", "/data/report.json"]
              env:
                - name: CLUSTER_NAME
                  value: {{ .Values.clusterName }}
              volumeMounts:
                - name: datapath
                  mountPath: /data
          containers:
            - image: "{{ include "cluster_job.image" . }}"
              args:
              - -config 
              - /jobs/conf/app.yaml
              name: accuknox-kiem-cronjob
              volumeMounts:
                - mountPath: /data
                  name: datapath    
                - name: secret-volume
                  mountPath: /secrets/tokens
                  readOnly: true
                - name: config
                  mountPath: /jobs/conf/app.yaml
                  subPath: app.yaml
                {{- if .Values.joinToken }}    
                - name: config
                  mountPath: /jobs/spire/agent.conf
                  subPath: agent.conf 
                - name: spirepath
                  mountPath: /run/spire/agent
                {{- end }}      
          terminationGracePeriodSeconds: 0
          volumes:
            - name: datapath
              emptyDir: {}
            - name: secret-volume
              secret:
                secretName: {{ .Values.secretName | default "kiem-job-auth-token" }}
            - name: config
              configMap:
                name: kiem-config-{{ .Release.Name }}
            {{- if .Values.joinToken }} 
            - name: spirepath
              emptyDir: {}
            {{- end }}
          restartPolicy: OnFailure
          serviceAccount: kiem-service-account


