apiVersion: batch/v1
kind: Job
metadata:
  name: kiem-job-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      labels:
        app: kiem-job-{{ now | unixEpoch }}
    spec:
    {{- if .Values.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.registry.secretName }}
    {{- end }}      
      initContainers:
        - name: kiem-init
          image: "{{ include "kiem.image" . }}"
          args: ["./kiem", "run", "--mode", "k8s", "--output", "/data/report.json"]
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
          volumeMounts:
            - name: datapath
              mountPath: /data
      containers:
        - image: "{{ include "cluster_job.image" . }}"
          command: ["/bin/sh", "-c"]
          args: ['./curl_command.sh']
          name: accuknox-kiem-job
          resources: {}
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: AUTH_TOKEN
                  {{- if (.Values.secretName | empty) }}
                  name: kiem-job-auth-token
                  {{- else }}
                  name: {{ .Values.secretName }}
                  {{- end }}
            - name: URL
              value: {{ .Values.URL }}
            - name: TENANT_ID
              value: {{ .Values.tenantID | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
            - name: LABEL_NAME
              value: {{ .Values.label | quote}}
            - name: CERT_BUNDLE_PATH
              value: {{ .Values.certBundlePath | quote }}   
            - name: CERT_BUNDLE_URL
              value: {{ .Values.certBundleURL }}
            - name: USE_INSECURE_CONNECTION
              value: {{ .Values.useInsecureConnection | quote }}
            - name: DATA_TYPE
              value: "KIEM"
          volumeMounts:
            - mountPath: /data
              name: datapath      
      volumes:
        - name: datapath
          emptyDir: {}
      restartPolicy: OnFailure
      serviceAccount: kiem-service-account
