apiVersion: batch/v1
kind: Job
metadata:
  name: kiem-job-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      labels:
        app: kiem-job-{{ now | unixEpoch }}
    spec:
    {{- if .Values.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.registry.secretName }}
    {{- end }}      
      initContainers:
        - name: kiem-init
          image: "{{ include "kiem.image" . }}"
          args: ["./kiem", "run", "--mode", "k8s", "--output", "/data/report.json"]
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
          volumeMounts:
            - name: datapath
              mountPath: /data
      containers:
        - image: "{{ include "cluster_job.image" . }}"
          command: ['sh', '-c', 'curl --location --request POST "https://${URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=KIEM&save_to_s3=true&label_id=${LABEL_NAME}" --header "Tenant-Id: ${TENANT_ID}" --header "Authorization: Bearer ${AUTH_TOKEN}" --form "file=@\"/data/report.json\""']
          name: accuknox-kiem-job
          resources: {}
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: AUTH_TOKEN
                  {{- if (.Values.secretName | empty) }}
                  name: kiem-job-auth-token
                  {{- else }}
                  name: {{ .Values.secretName }}
                  {{- end }}
            - name: URL
              value: {{ .Values.URL }}
            - name: TENANT_ID
              value: {{ .Values.tenantID | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
            - name: LABEL_NAME
              value: {{ .Values.label | quote}}
          volumeMounts:
            - mountPath: /data
              name: datapath      
      volumes:
        - name: datapath
          emptyDir: {}
      restartPolicy: OnFailure
      serviceAccount: kiem-service-account
