apiVersion: batch/v1
kind: Job
metadata:
  name: kiem-job-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      labels:
        app: kiem-job-{{ now | unixEpoch }}
    spec:
    {{- if .Values.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.registry.secretName }}
    {{- end }}      
      initContainers:
        - name: kiem-init
          image: "{{ include "kiem.image" . }}"
          args: ["./kiem", "run", "--mode", "k8s", "--output", "/data/report.json"]
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
          volumeMounts:
            - name: datapath
              mountPath: /data
      containers:
        - image: "{{ include "cluster_job.image" . }}"
          args:
          - -config 
          - /jobs/conf/app.yaml
          name: accuknox-kiem-job
          volumeMounts:
            - mountPath: /data
              name: datapath  
            - name: secret-volume
              mountPath: /secrets/tokens
              readOnly: true
            {{- if .Values.joinToken }}    
            - name: config
              mountPath: /jobs/spire/
              subPath: agent.conf 
            - name: spirepath
              mountPath: /run/spire/agent
            - name: config
              mountPath: /jobs/conf/
              subPath: app.yaml
            {{- end }}         
      volumes:
        - name: datapath
          emptyDir: {}
        - name: secret-volume
          secret:
            secretName: {{ .Values.secretName | default "kiem-job-auth-token" }}
        {{- if .Values.joinToken }} 
        - name: spirepath
          emptyDir: {}
        - name: config
          configMap:
            name: kiem-config-{{ .Release.Name }}
        {{- end }}
      restartPolicy: OnFailure
      serviceAccount: kiem-service-account
