apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-kiem-cluster-role
rules:
  - apiGroups:
        - ""
        - extensions
        - apps
        - rbac.authorization.k8s.io
        - roles.rbac.authorization.k8s.io
        - authorization.k8s.io
        - certificates.k8s.io
        - apiextensions.k8s.io
        - batch
    resources:  
        - namespaces
        - pods
        - serviceaccounts
        - roles
        - rolebindings
        - clusterroles
        - clusterrolebindings
        - deployments
        - replicasets
        - statefulsets
        - daemonsets
        - jobs
        - cronjobs
    verbs:
        - get
        - list
        - watch
---
{{- if .Values.joinToken }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "spire-cm-secrets-role-%s" .Release.Name }} 
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
{{- end }}