{{- if (eq (include "condition-feeder" .) "false") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: spire-agent-secret
  namespace: {{ .Release.Namespace }}
# This is expected to be empty by default and is used by
# agents-operator/spire-agent. Adding data to this will fail the startup of
# spire-agent
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: token-secret
  namespace: {{ .Release.Namespace }}
data:
  join_token: {{ .Values.global.agents.joinToken | b64enc | quote }}
  access_token: {{ .Values.global.agents.accessKey | b64enc | quote }}
{{- end }}
