apiVersion: v2
appVersion: v0.1.36
dependencies:
- condition: global.agents.enabled
  name: agents-chart
  repository: oci://public.ecr.aws/k9v9d5v2
  version: v0.11.23
- condition: kubearmor-operator.enabled
  name: kubearmor-operator
  repository: https://kubearmor.github.io/charts
  version: v1.6.6
- condition: global.cis.enabled
  name: cis-k8s-job
  repository: file://../kspm-jobs/cis-k8s-job
  version: 0.1.0
- condition: global.riskassessment.enabled
  name: k8s-risk-assessment-job
  repository: file://../kspm-jobs/k8s-risk-assessment-job
  version: 0.1.0
- condition: global.kiem.enabled
  name: kiem-job
  repository: file://../kspm-jobs/kiem-job
  version: 0.1.0
- condition: admissionController.enabled
  name: knoxguard-chart
  repository: oci://public.ecr.aws/k9v9d5v2
  version: v0.2.1
- condition: kyverno.enabled
  name: kyverno
  repository: oci://public.ecr.aws/k9v9d5v2
  version: v1.16.2
- condition: global.inClusterScan.enabled
  name: kubeshield-chart
  repository: oci://public.ecr.aws/k9v9d5v2
  version: v0.3.5
description: A Helm chart for Kubernetes
name: kspm-runtime
type: application
version: v0.1.36
