{{- if (eq (include "condition-feeder" .) "false") }}
{{- if not .Values.global.secretManagedByParent }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.global.spire.secretName }}"
  namespace: {{ .Release.Namespace }}
# This is expected to be empty by default and is used by
# agents-operator/spire-agent. Adding data to this will fail the startup of
# spire-agent
data: {}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: token-secret
  namespace: {{ .Release.Namespace }}
data:
  join_token: {{ include "joinToken" . }}
  access_token: {{ include "accessKey" . }}
{{- end }}
