apiVersion: batch/v1
kind: CronJob
metadata:
  name: kiem-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.global.cronTab }}"  
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: kiem-job
    spec:
      template:
        metadata:
          labels:
            app: scanner
        spec:
        {{- if .Values.global.registry.secretName }}
          imagePullSecrets:
          - name: {{ .Values.global.registry.secretName }}-kiem
        {{- end }}
          {{- if .Values.global.nodeSelector }}
          nodeSelector:
            {{- toYaml .Values.global.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.global.tolerations }}
          tolerations:
            {{- toYaml .Values.global.tolerations | nindent 12 }}
          {{- end }}
          initContainers:
            - name: kiem-init
              imagePullPolicy: IfNotPresent
              image: "{{ include "kiem.image" . }}"
              args: ["./kiem", "run", "--mode", "k8s", "--output", "/data/report.json"]
              env:
                - name: CLUSTER_NAME
                  value: "{{ .Values.global.clusterName }}"
              volumeMounts:
                - name: datapath
                  mountPath: /data
          containers:
            - image: "{{ include "cluster_job.image" . }}"
              args:
              - -config 
              - /jobs/conf/app.yaml
              imagePullPolicy: IfNotPresent
              name: accuknox-kiem-cronjob
              volumeMounts:
                - mountPath: /data
                  name: datapath    
                - name: secret-volume
                  mountPath: /secrets/tokens
                  readOnly: true
                - name: config
                  mountPath: /jobs/conf/app.yaml
                  subPath: app.yaml
              {{- if .Values.global.certEnabled }}
                - name: certs
                  mountPath: /certs
                  readOnly: true
              {{- end }}                  
                {{- if eq (include "spire.enabled" . ) "true" }}      
                - name: config
                  mountPath: /jobs/spire/agent.conf
                  subPath: agent.conf 
                - name: spirepath
                  mountPath: /run/spire/agent
                {{- end }}      
          terminationGracePeriodSeconds: 0
          volumes:
            - name: datapath
              emptyDir: {}
            - name: secret-volume
              secret:
                secretName: {{ .Values.global.secretName | default "jobs-token" }}
            - name: config
              configMap:
                name: kiem-config-{{ .Release.Name }}
          {{- if .Values.global.certEnabled }}
            - name: certs
              secret:
                secretName: {{ .Values.global.certSecretName | default "jobs-cert" }}
          {{- end }}                
            {{- if eq (include "spire.enabled" . ) "true" }}  
            - name: spirepath
              emptyDir: {}
            {{- end }}
          restartPolicy: OnFailure
          serviceAccount: kiem-service-account