apiVersion: batch/v1
kind: Job
metadata:
  name: kiem-job-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      labels:
        app: kiem-job-{{ now | unixEpoch }}
    spec:
    {{- if .Values.global.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.global.registry.secretName }}
    {{- end }}      
      initContainers:
        - name: kiem-init
          image: "{{ include "kiem.image" . }}"
          args: ["./kiem", "run", "--mode", "k8s", "--output", "/data/report.json"]
          env:
            - name: CLUSTER_NAME
              value: "{{ .Values.global.clusterName }}"
          volumeMounts:
            - name: datapath
              mountPath: /data
      containers:
        - image: "{{ include "cluster_job.image" . }}"
          command:
            - "./curl_command.sh"
          args:
            - -config
            - /jobs/conf/app.yaml
          name: accuknox-kiem-cronjob
          env:
            - name: AUTH_TOKEN
              value: {{ .Values.global.authToken | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.global.clusterName }}
            - name: URL     
              value: "{{ include "global.jobURL" . }}"
            - name: TENANT_ID
              value: {{ .Values.global.tenantId | quote }}
            - name: LABEL_NAME
              value: {{ .Values.global.label | quote }}
            - name: CERT_BUNDLE_PATH
              value: {{ .Values.global.certBundlePath | quote }}
            - name: CERT_BUNDLE_URL
              value: {{ .Values.global.certBundleURL | quote }}
            - name: USE_INSECURE_CONNECTION
              value: {{ .Values.global.useInsecureConnection | quote }}
            - name: DATA_TYPE
              value: "KIEM"
          volumeMounts:
            - mountPath: /data
              name: datapath  
            - name: secret-volume
              mountPath: /secrets/tokens
              readOnly: true
            - name: config
              mountPath: /jobs/conf/app.yaml
              subPath: app.yaml
            {{- if .Values.global.agents.joinToken }}    
            - name: config
              mountPath: /jobs/spire/agent.conf
              subPath: agent.conf 
            - name: spirepath
              mountPath: /run/spire/agent
            {{- end }}         
      volumes:
        - name: datapath
          emptyDir: {}
        - name: secret-volume
          secret:
            secretName: {{ .Values.global.secretName | default "jobs-token" }}
        - name: config
          configMap:
            name: kiem-config-{{ .Release.Name }}
        {{- if .Values.global.agents.joinToken }} 
        - name: spirepath
          emptyDir: {}
        {{- end }}
      restartPolicy: OnFailure
      serviceAccount: kiem-service-account