apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-api-cluster-role-binding
subjects:
- namespace: {{ .Release.Namespace }} 
  kind: ServiceAccount
  name: kiem-service-account 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-kiem-cluster-role
---
{{- if .Values.global.agents.joinToken }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "spire-cm-secrets-binding-kiem" 
  namespace: {{ .Release.Namespace }} 
subjects:
- kind: ServiceAccount
  name: kiem-service-account
  namespace: {{ .Release.Namespace }} 
roleRef:
  kind: Role
  name: {{ printf "spire-cm-secrets-role-%s" .Release.Name }} 
  apiGroup: rbac.authorization.k8s.io
{{- end }}
