# Default values for k8tls-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

accuknox:
  authToken: "NO-TOKEN-SET"
  cronTab: "30 9 * * *"
  tenantID: ""
  clusterName: ""
  label: ""
  URL: "cspm.demo.accuknox.com"
