apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: spire-agent-lease
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec: {}
