{{- if .Values.global.agents.joinToken }}
# create a secret managed by helm if join_token is present
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.spire.secretName }}
  namespace: {{ .Release.Namespace }}
data: {}
{{- end}}
---
{{- if (.Values.global.secretName | empty) }}
# if user didn't specify a secretName, use the default
apiVersion: v1
kind: Secret
metadata:
  name: jobs-token
  namespace: {{ .Release.Namespace }}
data:
  AUTH_TOKEN: {{ .Values.global.authToken | b64enc }}
  JOIN_TOKEN: {{ .Values.global.agents.joinToken | b64enc }}
{{- end }}