{{- if .Values.global.agents.joinToken }}
# create a secret managed by helm if join_token is present
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.spire.secretName }}
  namespace: {{ .Release.Namespace }}
data: {}
{{- end}}