apiVersion: batch/v1
kind: Job
metadata:
  name: k8tls-job-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      name: k8tls-job-{{ now | unixEpoch }}
    spec:
    {{- if .Values.global.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.global.registry.secretName }}
    {{- end }}     
      serviceAccountName: k8tls-serviceact
      containers:
      - image: "{{ include "cluster_job.image" . }}"
        command: ["/bin/sh", "-c"]
        args: ['curl --location --request POST "https://${URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=K8TLS&save_to_s3=true" --header "Tenant-Id: ${TENANT_ID}" --header "Authorization: Bearer ${AUTH_TOKEN}" --form "file=@\"/data/report.json\"" && cat /data/report.json']
        name: k8tls-job
        resources: {}
        env:
          - name: AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                key: AUTH_TOKEN
                {{- if (.Values.global.secretName | empty) }}
                name: k8tls-job-auth-token
                {{- else }}
                name: {{ .Values.global.secretName }}
                {{- end }}
          - name: URL
            value: {{ include "global.jobURL" . }}
          - name: TENANT_ID
            value: {{ .Values.global.tenantID | quote }}
          - name: CLUSTER_NAME
            value: {{ if ne .Values.global.clusterName "" }}{{ ".Values.global.clusterName" }}{{ else }}{{ "default" }}{{ end }}
          - name: LABEL_NAME
            value: {{ if ne .Values.global.label "" }}{{ .Values.global.label }}{{ else }}{{ "default" }}{{ end }}
        volumeMounts:
          - mountPath: /data
            name: datapath
      initContainers:
      - command: ["/bin/sh", "-c"]
        args: ["./k8s_tlsscan"]
        image: "{{ include "k8tls.image" . }}"
        name: k8tls
        env:
          - name: JSON
            value: "/data/report.json"
        volumeMounts:
        - mountPath: /data
          name: datapath
      restartPolicy: Never
      volumes:
        - name: datapath
          emptyDir: {}

