apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8tls-serviceact
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-k8tls-cr
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-k8tls-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-k8tls-cr
subjects:
- kind: ServiceAccount
  name: k8tls-serviceact
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8tls-job
  namespace: {{ .Release.Namespace }}
spec:
  jobTemplate:
    metadata:
      name: k8tls-job
    spec:
      template:
        spec:
        {{- if .Values.global.registry.secretName }}
          imagePullSecrets:
          - name: {{ .Values.global.registry.secretName }}
        {{- end }}  
          serviceAccountName: k8tls-serviceact
          containers:
          - image:  "{{ include "cluster_job.image" . }}"
            workingDir: /app
            command: ["/bin/sh", "-c"]
            args: ['./curl_command.sh']
            name: k8tls-job
            resources: {}
            env:
              - name: AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: AUTH_TOKEN
                    {{- if (.Values.secretName | empty) }}
                    name: k8tls-job-auth-token
                    {{- else }}
                    name: {{ .Values.secretName }}
                    {{- end }}
              - name: AUTH_TOKEN
                value: {{ .Values.global.authToken | quote }}
              - name: URL
                value: "{{ include "global.jobURL" . }}"
              - name: TENANT_ID
                value: {{ .Values.global.tenantId | quote }}
              - name: LABEL_NAME
                value: {{ .Values.global.label | quote }}
              - name: URL
                value: {{ .Values.URL }}
              - name: TENANT_ID
                value: {{ .Values.tenantID | quote }}
              - name: CLUSTER_NAME
                value: {{ if ne .Values.clusterName "" }}{{ ".Values.global.clusterName" }}{{ else }}{{ "default" }}{{ end }}
              - name: LABEL_NAME
                value: {{ if ne .Values.label "" }}{{ .Values.label }}{{ else }}{{ "default" }}{{ end }}
              - name: CERT_BUNDLE_PATH
                value: {{ .Values.global.certBundlePath | quote }}    
              - name: CERT_BUNDLE_URL
                value: {{ .Values.global.certBundleURL }}
              - name: USE_INSECURE_CONNECTION
                value: {{ .Values.global.useInsecureConnection | quote }}
              - name: DATA_TYPE
                value: "K8TLS" 
            volumeMounts:
              - mountPath: /data
                name: datapath
          initContainers:
          - command: ["/bin/sh", "-c"]
            args: ["./k8s_tlsscan"]
            image: "{{ include "k8tls.image" . }}"
            name: k8tls
            env:
              - name: JSON
                value: "/data/report.json"
            volumeMounts:
            - mountPath: /data
              name: datapath
          restartPolicy: Never
          volumes:
            - name: datapath
              emptyDir: {}

  schedule: "{{ .Values.cronTab }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
