  {{- if (.Values.global.secretName | empty) }}
# if user didn't specify a secretName, use the default
apiVersion: v1
kind: Secret
metadata:
  name: k8tls-job-auth-token
  namespace: {{ .Release.Namespace }}
data:
  AUTH_TOKEN: {{ .Values.global.authToken | b64enc }}
{{- end }}
