# Default values for cis-k8s-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registryName: public.ecr.aws/k9v9d5v2

cluster_job:
  repository: knoxjobs
  tag: "v0.1.8"
  image: ""

kubeBench:
  owner: docker.io/aquasec
  repository: kube-bench
  tag: "v0.15.0"
  image: ""


global:
  authToken: ""
  enableJobsUrl: false
  tenantId: ""
  cronTab: ""
  clusterName: ""
  label: ""
  secretName: ""
  joinToken: ""
  accessKey: ""

  cis:
    toolConfig:
      platform: ""
      nodeType: ""
      targets: ""
      benchmark: ""
      check: ""
      skip: ""

  spire:
    secretName: "spire-agent-secret"

  certPath: ""  # Set this for cert local path if needed .
  certURL: ""  # Set this for cert URL if needed (if certPath is set as well certPath will take precedent)
  skipTLSVerification: false  # Set to true if insecure connection is needed

  nodeSelector: {} # Node selector for scheduling the job --set nodeSelector."kubernetes.io/os"=linux
  tolerations: [] # Tolerations for scheduling pods on tainted nodes e.g. --set global.tolerations[0].key=dedicated --set global.tolerations[0].operator=Equal --set global.tolerations[0].value=accuknox --set global.tolerations[0].effect=NoSchedule

  # To use existing secret updated {global.registry.secretName} with your secret name.
  registry:
    url: ""
    secretName: ""
    username: ""
    password: ""
    preserveUpstream: true

authTokenPath: "/secrets/tokens/AUTH_TOKEN"
joinTokenPath: "/secrets/tokens/JOIN_TOKEN"
accessKeyPath: "/secrets/tokens/ACCESS_KEY"

spireHost: "localhost"
spirePort: 8081
knoxGateway: "kgw:8080"
spireConfigFile: "/jobs/spire/agent.conf"
tokenURL: "localhost"


configPaths:
- "/data/kubescape-cache/allcontrols.json"
- "/data/kubescape-cache/clusterscan.json"
- "/data/kubescape-cache/mitre.json"
- "/data/kubescape-cache/nsa.json"