# Default values for cis-k8s-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster_job:
  owner: public.ecr.aws/k9v9d5v2
  repository: cluster-job
  tag: "latest-onprem"
  image: ""

kubeBench:
  owner: docker.io/aquasec
  repository: kube-bench
  tag: "v0.9.1"
  image: ""



toolConfig:
  platform: ""
  nodeType: "worker"
  targets: ""
  benchmark: ""
  check: ""
  skip: ""

global:
  authToken: ""
  enableJobsUrl: false
  tenantId: ""
  cronTab: ""
  clusterName: ""
  label: ""
  secretName: ""
  joinToken: ""

  spire:
    secretName: "spire-agent-secret"

  certBundlePath: ""  # Set this for cert local path if needed .
  certBundleURL: ""  # Set this for cert URL if needed (if certBundlePath is set as well certBundlePath will take precedent)
  useInsecureConnection: false  # Set to true if insecure connection is needed

  # To use existing secret updated {registry.secretName} with your secret name.
  registry: 
    url: ""
    secretName: ""
    username: ""
    password: ""
    preserveUpstream: true

authTokenPath: "/secrets/tokens/AUTH_TOKEN"
joinTokenPath: "/secrets/tokens/JOIN_TOKEN"

spireHost: "localhost"
spirePort: 8081
knoxGateway: "kgw:8080"
spireConfigFile: "/jobs/spire/agent.conf"


configPaths:
- "/data/kubescape-cache/allcontrols.json"
- "/data/kubescape-cache/clusterscan.json"
- "/data/kubescape-cache/mitre.json"
- "/data/kubescape-cache/nsa.json"