localAgent:
  metadata: 
    name: "local-scanning-agent"
    
  registry-scanning:
      chart-name: oci://public.ecr.aws/k9v9d5v2/registry-scan
      chart-version: v0.3.0

  trivyDB:
    secretName: {{ .Values.registry.secretName }}
    dockerConfigPath: "/home/default/.docker/config.json" 

  server:
    endpoints:
      getRegistries: https://{{ include "agents.ppsHost" . }}/pps/api/v1/registries/fetch-registries
      getArtifactToken: https://{{ include "agents.ppsHost" . }}/pps/api/v1/registries/artifact-token
      updateregistrystatus: https://{{ include "agents.ppsHost" . }}/pps/api/v1/registries/change-status
    interval: "10s"
    queue: "false"
    
  security:
    enable: true
    agent: agents-operator.agents.svc.cluster.local:9091
    kmuxConfigFilePath: "/var/lib/local-agent/kmux/spire/config.yaml"
    isK8s: true
    
  rabbitmq:
    username: "example-user"
    password: "1E758F90-0092-4400-8713-EAD9FF591F75"
