# Default values for k8s-risk-assessment-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubescape:
  image:
    repository: quay.io/kubescape/kubescape-cli
    tag: "v3.0.8"

replicaCount: 1

accuknox:
  authToken: "NO-TOKEN-SET"
  URL: "cspm.demo.accuknox.com"
  tenantID: ""
  cronTab: "30 9 * * *"
  clusterName: ""
  clusterID: 0
  label: ""
