# Default values for k8s-risk-assessment-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubescape:
  image:
    repository: quay.io/kubescape/kubescape-cli
    tag: "v3.0.8"

replicaCount: 1

accuknox:
  riskassessment:
    enabled: "false"
  secretName: ""
