apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discoveryEngine.name" . }}-sumengine
  namespace: {{ .Release.Namespace }}
data:
  app.yaml: |-
    {{ toYaml .Values.discoveryEngine.summaryEngine.appConfig | nindent 4 }}
  kmux.yaml: |-
    {{ toYaml .Values.discoveryEngine.summaryEngine.kmuxConfig | nindent 4 }}
  sensitive-data-rules.yaml: |-
    {{ .Files.Get "discoveryEngine/configmap/sensitive-data-rules.yaml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discoveryEngine.name" . }}-offloader
  namespace: {{ .Release.Namespace }}
data:
  app.yaml: |-
    {{ toYaml .Values.discoveryEngine.offloader.appConfig | nindent 4 }}
  kmux.yaml: |-
    {{ toYaml .Values.discoveryEngine.offloader.kmuxConfig | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discoveryEngine.name" . }}-hardening
  namespace: {{ .Release.Namespace }}
data:
  app.yaml: |-
    {{ toYaml .Values.discoveryEngine.hardening.appConfig | nindent 4 }}
  kmux.yaml: |-
    {{ toYaml .Values.discoveryEngine.hardening.kmuxConfig | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discoveryEngine.name" . }}-discover
  namespace: {{ .Release.Namespace }}
data:
  app.yaml: |-
    {{ toYaml .Values.discoveryEngine.discover.appConfig | nindent 4 }}
  kmux.yaml: |-
    {{ toYaml .Values.discoveryEngine.discover.kmuxConfig | nindent 4 }}
