apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "discoveryEngine.name" . }}
  name: {{ include "discoveryEngine.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.discoveryEngine.replicaCount | default 0 }}
  selector:
    matchLabels:
      app: {{ include "discoveryEngine.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "discoveryEngine.name" . }}
    spec:
      serviceAccountName: discovery-engine
      terminationGracePeriodSeconds: 10
      containers:
        {{- if .Values.discoveryEngine.summaryEngine.enabled }}
        - name: summary-engine
          image: "{{ include "summaryEngine.image" . }}"  #"{{ .Values.discoveryEngine.imagebase }}-sumengine:{{ .Values.discoveryEngine.tag }}"
          imagePullPolicy: Always
          args: ["--config", "/var/lib/sumengine/app.yaml", "--kmux-config", "/var/lib/sumengine/kmux.yaml"]
          resources:
            {{- toYaml .Values.discoveryEngine.summaryEngine.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /var/lib/sumengine/
            name: config-sumengine
            readOnly: true
        {{- end }}
        {{- if .Values.discoveryEngine.offloader.enabled }}
        - name: offloader
          image: "{{ include "offloader.image" . }}" #"{{ .Values.discoveryEngine.imagebase }}-offloader:{{ .Values.discoveryEngine.tag }}"
          imagePullPolicy: Always
          args: ["--config", "/var/lib/offloader/app.yaml", "--kmux-config", "/var/lib/offloader/kmux.yaml"]
          ports:
          - containerPort: 8090
            name: grpc
          resources:
            {{- toYaml .Values.discoveryEngine.offloader.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /var/lib/offloader/
            name: config-offloader
            readOnly: true
        {{- end }}
        {{- if .Values.discoveryEngine.rabbitmq.enabled }}
        - name: rabbitmq
          image: {{ .Values.discoveryEngine.rabbitmq.image.repository }}:{{ .Values.discoveryEngine.rabbitmq.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          resources:
            {{- toYaml .Values.discoveryEngine.rabbitmq.resources | nindent 12 }}
        {{- end }}
        {{- if .Values.discoveryEngine.discover.enabled }}
        - name: discover
          image: "{{ include "discover.image" . }}"   # "{{ .Values.discoveryEngine.imagebase }}-discover:{{ .Values.discoveryEngine.tag }}"
          imagePullPolicy: Always
          args: ["--config", "/var/lib/discover/app.yaml", "--kmux-config", "/var/lib/discover/kmux.yaml"]
          env:
          - name: ENABLE_GRPC
            value: {{ .Values.discoveryEngine.offloader.enabled | quote }}
          ports:
          - containerPort: 8090
            name: grpc
          resources:
            {{- toYaml .Values.discoveryEngine.discover.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /var/lib/discover/
            name: config-discover
            readOnly: true
        {{- end }}
        {{- if .Values.discoveryEngine.hardening.enabled }}
        - name: hardening
          image: "{{ include "hardening.image" . }}" # "{{ .Values.discoveryEngine.imagebase }}-hardening:{{ .Values.discoveryEngine.tag }}"
          imagePullPolicy: Always
          args: ["start", "--config", "/var/lib/hardening/config/app.yaml", "--kmux-config", "/var/lib/hardening/config/kmux.yaml", "--templates", "/var/lib/hardening/resources/policy_templates.zip"]
          resources:
            {{- toYaml .Values.discoveryEngine.hardening.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /var/lib/hardening/config/
            name: config-hardening
            readOnly: true
      {{- end }}
      {{- if .Values.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.registry.secretName | quote }}
      {{- end }}
      volumes:
      {{- if .Values.discoveryEngine.summaryEngine.enabled }}
      - configMap:
          name: {{ include "discoveryEngine.name" . }}-sumengine
        name: config-sumengine
      {{- end }}
      {{- if .Values.discoveryEngine.offloader.enabled }}
      - configMap:
          name: {{ include "discoveryEngine.name" . }}-offloader
        name: config-offloader
      {{- end }}
      {{- if .Values.discoveryEngine.hardening.enabled }}
      - configMap:
          name: {{ include "discoveryEngine.name" . }}-hardening
        name: config-hardening
      {{- end }}
      {{- if .Values.discoveryEngine.discover.enabled }}
      - configMap:
          name: {{ include "discoveryEngine.name" . }}-discover
        name: config-discover
      {{- end }}