apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "discoveryEngine.name" . }}
  name: {{ include "discoveryEngine.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: grpc
      port: 8090
      protocol: TCP
      targetPort: 8090
    - name: amqp  
      port: 5672
      protocol: TCP
      targetPort: 5672  
  selector:
    app: {{ include "discoveryEngine.name" . }}
