apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-vars
  namespace: {{ .Release.Namespace }}
data:
  {{- range $k, $v := .Values.feederService.ciliumVars }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote -}}
  {{- else }}
  {{ $k }}:  ""
  {{- end }}
  {{- end }} 
