apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-engine-vars
  namespace: {{ .Release.Namespace }}
data:
  DISCOVERYENGINE_URL: "discovery-engine.{{ .Release.Namespace }}.svc.cluster.local" 
  {{- range $k, $v := .Values.feederService.discoveryEngineVars }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote -}}
  {{- else }}
  {{ $k }}:  ""
  {{- end }}
  {{- end }} 
