apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-vars
data:
  SPIRE_AGENT_URL: "agents-operator.{{ .Release.Namespace }}.svc.cluster.local:9091"
  {{- range $k, $v := .Values.agentsOperator.spireVars }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote -}}
  {{- else }}
  {{ $k }}:  ""
  {{- end }}
  {{- end }}  