apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-vars
data:
  {{- range $k, $v := .Values.feederService.splunkVars }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote -}}
  {{- else }}
  {{ $k }}:  ""
  {{- end }}
  {{- end }} 
