{{- if (eq (include "condition-feeder" .) "false") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "policyEnforcementAgent.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "policyEnforcementAgent.name" . }}
spec:
  replicas: {{ .Values.policyEnforcementAgent.replicaCount | default 0 }}
  selector:
    matchLabels:
      app: {{ include "policyEnforcementAgent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "policyEnforcementAgent.name" . }}
    spec:
      serviceAccountName: {{ include "policyEnforcementAgent.name" . }}
      containers:
      - name: {{ include "policyEnforcementAgent.name" . }}
        image: "{{ include "policyEnforcementAgent.image" . }}"   #"{{ .Values.policyEnforcementAgent.image }}:{{ .Values.policyEnforcementAgent.tag }}"
        imagePullPolicy: Always
        args:
        - --config-path=/var/lib/pea
        volumeMounts:
        - mountPath: /var/lib/pea/application.yaml
          name: {{ include "policyEnforcementAgent.name" . }}
          subPath: application.yaml
        {{- with .Values.policyEnforcementAgent.volumesMounts -}}
        {{- toYaml . | nindent 6 }}
        {{- end }}     
        resources:
        {{- if .Values.policyEnforcementAgent.resources }}
          {{- toYaml .Values.policyEnforcementAgent.resources | nindent 10 }}
        {{- else }}
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 50Mi
        {{- end }}
        env:
        {{- include "onboarding.details" . | nindent 8 }}
        {{- if .Values.policyEnforcementAgent.liveness }}
        livenessProbe:
          exec:
            command:
            - curl
            - -Iv
            - "{{ include "agents.spireHost" . }}:{{ .Values.agentsOperator.ports.health | default 9090 }}/live"
          initialDelaySeconds: 60
          failureThreshold: 1
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 15   
        {{- end}}
      {{- if .Values.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.registry.secretName | quote }}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 484
          name: {{ include "policyEnforcementAgent.name" . }}
        name: {{ include "policyEnforcementAgent.name" . }}    
      {{- with .Values.policyEnforcementAgent.volumes -}}
      {{- toYaml . | nindent 6 }}
      {{- end }}   
{{- end }}    
   