apiVersion: batch/v1
kind: Job
metadata:
  name: k8tls-job-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      name: k8tls-job-{{ now | unixEpoch }}
    spec:
    {{- if .Values.registry.secretName }}
      imagePullSecrets:
      - name: {{ .Values.registry.secretName }}
    {{- end }}     
      serviceAccountName: k8tls-serviceact
      containers:
      - image: "{{ include "cluster_job.image" . }}"
        command: ["/bin/sh", "-c"]
        args: ['./curl_command.sh']
        name: k8tls-job
        resources: {}
        env:
          - name: AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                key: AUTH_TOKEN
                {{- if (.Values.secretName | empty) }}
                name: k8tls-job-auth-token
                {{- else }}
                name: {{ .Values.secretName }}
                {{- end }}
          - name: URL
            value: {{ .Values.URL }}
          - name: TENANT_ID
            value: {{ .Values.tenantID | quote }}
          - name: CLUSTER_NAME
            value: {{ if ne .Values.clusterName "" }}{{ .Values.clusterName }}{{ else }}{{ "default" }}{{ end }}
          - name: LABEL_NAME
            value: {{ if ne .Values.label "" }}{{ .Values.label }}{{ else }}{{ "default" }}{{ end }}
          - name: CERT_BUNDLE_PATH
            value: {{ .Values.certBundlePath | quote }}   
          - name: CERT_BUNDLE_URL
            value: {{ .Values.certBundleURL }}
          - name: USE_INSECURE_CONNECTION
            value: {{ .Values.useInsecureConnection | quote }}
          - name: DATA_TYPE
            value: "K8TLS"
        volumeMounts:
          - mountPath: /data
            name: datapath
      initContainers:
      - command: ["/bin/sh", "-c"]
        args: ["./k8s_tlsscan"]
        image: "{{ include "k8tls.image" . }}"
        name: k8tls
        env:
          - name: JSON
            value: "/data/report.json"
        volumeMounts:
        - mountPath: /data
          name: datapath
      restartPolicy: Never
      volumes:
        - name: datapath
          emptyDir: {}

