apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8tls-serviceact
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-k8tls-cr
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-k8tls-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-k8tls-cr
subjects:
- kind: ServiceAccount
  name: k8tls-serviceact
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8tls-job
  namespace: {{ .Release.Namespace }}
spec:
  jobTemplate:
    metadata:
      name: k8tls-job
    spec:
      template:
        spec:
        {{- if .Values.imagePullSecrets.name }}
          imagePullSecrets:
          - name: {{ .Values.imagePullSecrets.name }}
        {{- end }}
          serviceAccountName: k8tls-serviceact
          containers:
          - image:  "{{ .Values.accuknoxJob.image.repository }}:{{ .Values.accuknoxJob.image.tag }}"
            command: ["/bin/sh", "-c"]
            args: ['curl --location --request POST "https://${URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=K8TLS&save_to_s3=true" --header "Tenant-Id: ${TENANT_ID}" --header "Authorization: Bearer ${AUTH_TOKEN}" --form "file=@\"/data/report.json\"" && cat /data/report.json']
            name: k8tls-job
            resources: {}
            env:
              - name: AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: AUTH_TOKEN
                    {{- if (.Values.accuknox.secretName | empty) }}
                    name: k8tls-job-auth-token
                    {{- else }}
                    name: {{ .Values.accuknox.secretName }}
                    {{- end }}
              - name: URL
                value: {{ .Values.accuknox.URL }}
              - name: TENANT_ID
                value: {{ .Values.accuknox.tenantID | quote }}
              - name: CLUSTER_NAME
                value: {{ if ne .Values.accuknox.clusterName "" }}{{ .Values.accuknox.clusterName }}{{ else }}{{ "default" }}{{ end }}
              - name: LABEL_NAME
                value: {{ if ne .Values.accuknox.label "" }}{{ .Values.accuknox.label }}{{ else }}{{ "default" }}{{ end }}
            volumeMounts:
              - mountPath: /data
                name: datapath
          initContainers:
          - command: ["/bin/sh", "-c"]
            args: ["./k8s_tlsscan"]
            image: "{{ .Values.k8tls.image.repository }}:{{ .Values.k8tls.image.tag }}"
            name: k8tls
            env:
              - name: JSON
                value: "/data/report.json"
            volumeMounts:
            - mountPath: /data
              name: datapath
          restartPolicy: Never
          volumes:
            - name: datapath
              emptyDir: {}

  schedule: "{{ .Values.accuknox.cronTab }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
