{{- if (.Values.accuknox.secretName | empty) }}
# if user didn't specify a secretName, use the default
apiVersion: v1
kind: Secret
metadata:
  name: k8tls-job-auth-token
  namespace: {{ .Release.Namespace }}
data:
  AUTH_TOKEN: {{ .Values.accuknox.authToken | b64enc }}
{{- end }}
---
{{- if .Values.spire.joinToken }}
# create a secret managed by helm if join_token is present
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spire.secretName | default (printf "spire-agent-secret-%s" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
data: {}
{{- end }}