# Default values for kiem-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

accuknox:
  authToken: "NO-TOKEN-SET"
  URL: "cspm.demo.accuknox.com"
  tenantID: ""
  cronTab: "30 9 * * *"
  clusterName: ""
  label: ""
