# Default values for kiem-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


cluster_job:
  owner: public.ecr.aws/k9v9d5v2
  repository: knoxjobs
  tag: "v0.1.2"
  image: ""

kiem:
  owner: accuknox
  repository: kiem
  tag: "latest"
  image: ""

# To use existing secret updated {registry.secretName} with your secret name.
registry: 
  url: ""
  secretName: ""
  username: ""
  password: ""
  preserveUpstream: true


replicaCount: 1

global:
  authToken: ""
  enableJobsUrl: false
  tenantId: ""
  cronTab: ""
  clusterName: ""
  label: ""
  secretName: ""
  joinToken: ""

  spire:
    secretName: "spire-agent-secret"


authTokenPath: "/secrets/tokens/AUTH_TOKEN"
joinTokenPath: "/secrets/tokens/JOIN_TOKEN"

spirePort: 8081
spireConfigFile: "/jobs/spire/agent.conf"


configPaths:
- "/data/kubescape-cache/allcontrols.json"
- "/data/kubescape-cache/clusterscan.json"
- "/data/kubescape-cache/mitre.json"
- "/data/kubescape-cache/nsa.json"