# Default values for kiem-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster_job:
  owner: public.ecr.aws/k9v9d5v2
  repository: knoxjobs
  tag: "v0.1.7"
  image: ""
  
kiem:
  owner: accuknox
  repository: kiem
  tag: "latest"
  image: ""


replicaCount: 1

global:
  authToken: ""
  enableJobsUrl: false
  tenantId: ""
  cronTab: ""
  clusterName: ""
  label: ""
  secretName: ""
  joinToken: ""
  accessKey: ""

  spire:
    secretName: "spire-agent-secret"

  certPath: ""  # Set this for cert local path if needed .
  certURL: ""  # Set this for cert URL if needed (if certPath is set as well certPath will take precedent)
  skipTLSVerification: false  # Set to true if insecure connection is needed

  # To use existing secret updated {global.registry.secretName} with your secret name.
  registry: 
    url: ""
    secretName: ""
    username: ""
    password: ""
    preserveUpstream: true

authTokenPath: "/secrets/tokens/AUTH_TOKEN"
joinTokenPath: "/secrets/tokens/JOIN_TOKEN"
accessKeyPath: "/secrets/tokens/ACCESS_KEY"


spirePort: 8081
spireConfigFile: "/jobs/spire/agent.conf"


configPaths:
- "/data/kubescape-cache/allcontrols.json"
- "/data/kubescape-cache/clusterscan.json"
- "/data/kubescape-cache/mitre.json"
- "/data/kubescape-cache/nsa.json"