name: "Mandatory Approvers Check"

on:
  pull_request:
    branches:
      - "jobs-consol"
    paths:
      - "**"
      
jobs:
  check-approvers:
    name: Check required approvals
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
      checks: write

    steps:
      - name: Require specific approvers
        uses: Automattic/action-required-review@v3
        with:
          # GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          requirements: |
            - name: KSPM runtime changes
              paths:
                - 'kspm-runtime/**'
              users:
                - kprateep
                - seswarrajan
                - Priyaccuknox
              teams: []   
          fail: true
